apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pv-claim
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: synapse
spec:
  selector:
    matchLabels:
      app: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
      - image: matrixdotorg/synapse:v1.62.0
      #- image: ubuntu:latest
       # command: [ "/bin/sleep", "3650d" ]
        name: synapse
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
          - containerPort: 8008
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: synapse-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
  name: synapse-service
  namespace: synapse
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8008
      protocol: TCP
      targetPort: 8008
  selector:
    app: synapse
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-ingress
  namespace: synapse
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
spec:
  ingressClassName: nginx
  rules:
    - host: synapse.groupdrive.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse-service
                port:
                  number: 8008
  tls:
    - hosts:
        - synapse.groupdrive.app
      secretName: synapse-tls
