version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:3000"
    environment:
      ENV: "local"
      PGHOST: 'postgres_database'
      PGUSER: 'postgres'
      PGDATABASE: 'group_drive'
      PGPASSWORD: 'example'
      PGPORT: 5432
    volumes:
      - ./app/:/usr/src/app
      - ./log:/var/log
#    depends_on:
#      - postgres_database
#      - mongo_db
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    container_name: postgres_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: group_drive

  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example